[workspace]
members = [
    "day01A", "day01B", "day02A", "day02B", "day03A", "day03B", "day04A", "day04B", "day05A", "day05B",
]


[build]
rustflags = [
  "-C", "debuginfo=2",
  "-C", "split-debuginfo=unpacked"
]
